<a href="https://colab.research.google.com/github/nirjalalala/learn_ml/blob/main/Day_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Creating a numpy array and its attributes**

In [20]:
#Importing numpy library
import numpy as np

In [19]:
#creating a list named "my_list"
my_list = [1,2,3,4,5]

#Creating a 1-D numpy array from "my_list"
my_arr = np.array(my_list)

#creating a 0-D array
arr_0d = np.array(42)
print("\n0-D array:")
print(arr_0d)

#creating a 2-D array
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("\n2-D array:")
print(arr_2d)

 #creating a 3_D array
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("\n3-D array:")
print(arr_3d)


0-D array:
42

2-D array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

3-D array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [22]:
#creating array and its attributes
arr = np.array([[1,2,3],[4,5,6]])
print("\nArray :",end="\t")
print(arr)
print("\n Shape:",end="\t")
print(arr.shape)
print("\n No. of dimensions:",end="\t")
print(arr.ndim)
print("\n Data Type:",end="\t")
print(arr.dtype)
print("\n Size:",end="\t")
print(arr.size)
print("\n Item size:",end="\t")
print(arr.itemsize)


Array :
[[1 2 3]
 [4 5 6]]

 Shape:	(2, 3)

 No. of dimensions:	2

 Data Type:	int64

 Size:	6

 Item size:	8


#**Accessing and Manipulating array elements**

In [33]:
#Accessing 1-D array elements
my_arr = np.arange(1,10)  # from 1 to 9
print(my_arr[2])  #third element in the array

3


In [29]:
#Accessing 2-D array elements
my_arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(my_arr[1,2])

8


In [30]:
#Accessing 3-D array elements
my_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(my_arr[1,1,2])

12


##Negative Inexing

In [32]:
#Accessing 2-D array elements
my_arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(my_arr[1,-2])   # second row, second-last element

9


##Slicing Arrays

In [37]:
arr = np.arange(1,22,2) #odd numbers from 1 to 22

#Slicing
print(arr[1:5])   #elements from index 1 to 4

#Slicing with step
print(arr[1:5:2]) #elements from index 1 to 4 with step 2

#slicing with negative index
print(arr[3:-1]) #elements from index 3 to -1
print(arr[-3:-1]) #elements from index -3 to -1

[3 5 7 9]
[3 7]
[ 7  9 11 13 15 17 19]
[17 19]


In [41]:
#Slicing a 2-D numpy array

arr = np.arange(1,11).reshape(5,2)
print(arr)

print("\nAfter Slicing:")
print(arr[1:4,0:2])  #row 1 to row 3  , Column 0 to Column 1

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

After Slicing:
[[3 4]
 [5 6]
 [7 8]]


In [61]:
#Slicing a 3-D numpy array
arr = np.arange(1,28).reshape(3,3,3)
print(arr)

print("\nAfter Slicing:")
print(arr[1:3,:2,-2:-1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

After Slicing:
[[[11]
  [14]]

 [[20]
  [23]]]


#**Solved Questions**

1. Create a NumPy array from the list [7,14,21,28]. Print the array.

In [42]:
arr = np.array([7,14,21,28])
print(arr)

[ 7 14 21 28]


2. Create a 2D NumPy array [[5,10,15],[20,25,30]]. Print its shape and number of dimensions.

In [43]:
arr = np.array([[5,10,15],[20,25,30]])
print(arr.shape)
print(arr.ndim)

(2, 3)
2


3. Use np.zeros to create a 2D array of shape (2,3). Then, use np.arange to create an array from 0 to 12 with a step of 3. Print both arrays.

In [45]:
a = np.zeros((2,3))
b = np.arange(0,13,3)
print(a)
print("\n")
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


[ 0  3  6  9 12]


4. Create a NumPy array [2,4,6,8]. Multiply all elements by 3 and print the result.

In [47]:
a = np.array([2,4,6,8])
b = a*3
print(b)


[ 6 12 18 24]


5. Create a NumPy array [1,3,5,7,9,11]. Print the third element and a slice from index 1 to 3 (inclusive).

In [49]:
a = np.arange(1,12,2)
print("Third element = ", end = " ")
print(a[2])
print("\nSlice form index 1 to 3 (inclusive) =", end= " ")
print(a[1:4])

Third element =  5

 Slice form index 1 to 3 (inclusive) = [3 5 7]
