<a href="https://colab.research.google.com/github/nirjalalala/learn_ml/blob/main/Day_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Creating a numpy array and its attributes**

In [1]:
#Importing numpy library
import numpy as np

In [ ]:
#creating a list named "my_list"
my_list = [1,2,3,4,5]

#Creating a 1-D numpy array from "my_list"
my_arr = np.array(my_list)

#creating a 0-D array
arr_0d = np.array(42)
print("\n0-D array:")
print(arr_0d)

#creating a 2-D array
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("\n2-D array:")
print(arr_2d)

 #creating a 3_D array
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("\n3-D array:")
print(arr_3d)


0-D array:
42

2-D array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

3-D array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#creating array and its attributes
arr = np.array([[1,2,3],[4,5,6]])
print("\nArray :",end="\t")
print(arr)
print("\n Shape:",end="\t")
print(arr.shape)
print("\n No. of dimensions:",end="\t")
print(arr.ndim)
print("\n Data Type:",end="\t")
print(arr.dtype)
print("\n Size:",end="\t")
print(arr.size)
print("\n Item size:",end="\t")
print(arr.itemsize)


Array :
[[1 2 3]
 [4 5 6]]

 Shape:	(2, 3)

 No. of dimensions:	2

 Data Type:	int64

 Size:	6

 Item size:	8


#**Accessing and Manipulating array elements**

In [ ]:
#Accessing 1-D array elements
my_arr = np.arange(1,10)  # from 1 to 9
print(my_arr[2])  #third element in the array

3


In [ ]:
#Accessing 2-D array elements
my_arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(my_arr[1,2])

8


In [ ]:
#Accessing 3-D array elements
my_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(my_arr[1,1,2])

12


##Negative Inexing

In [ ]:
#Accessing 2-D array elements
my_arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(my_arr[1,-2])   # second row, second-last element

9


##Slicing Arrays

In [ ]:
arr = np.arange(1,22,2) #odd numbers from 1 to 22

#Slicing
print(arr[1:5])   #elements from index 1 to 4

#Slicing with step
print(arr[1:5:2]) #elements from index 1 to 4 with step 2

#slicing with negative index
print(arr[3:-1]) #elements from index 3 to -1
print(arr[-3:-1]) #elements from index -3 to -1

[3 5 7 9]
[3 7]
[ 7  9 11 13 15 17 19]
[17 19]


In [ ]:
#Slicing a 2-D numpy array

arr = np.arange(1,11).reshape(5,2)
print(arr)

print("\nAfter Slicing:")
print(arr[1:4,0:2])  #row 1 to row 3  , Column 0 to Column 1

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

After Slicing:
[[3 4]
 [5 6]
 [7 8]]


In [ ]:
#Slicing a 3-D numpy array
arr = np.arange(1,28).reshape(3,3,3)
print(arr)

print("\nAfter Slicing:")
print(arr[1:3,:2,-2:-1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

After Slicing:
[[[11]
  [14]]

 [[20]
  [23]]]


#**Solved Questions**

1. Create a NumPy array from the list [7,14,21,28]. Print the array.

In [ ]:
arr = np.array([7,14,21,28])
print(arr)

[ 7 14 21 28]


2. Create a 2D NumPy array [[5,10,15],[20,25,30]]. Print its shape and number of dimensions.

In [ ]:
arr = np.array([[5,10,15],[20,25,30]])
print(arr.shape)
print(arr.ndim)

(2, 3)
2


3. Use np.zeros to create a 2D array of shape (2,3). Then, use np.arange to create an array from 0 to 12 with a step of 3. Print both arrays.

In [ ]:
a = np.zeros((2,3))
b = np.arange(0,13,3)
print(a)
print("\n")
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


[ 0  3  6  9 12]


4. Create a NumPy array [2,4,6,8]. Multiply all elements by 3 and print the result.

In [ ]:
a = np.array([2,4,6,8])
b = a*3
print(b)


[ 6 12 18 24]


5. Create a NumPy array [1,3,5,7,9,11]. Print the third element and a slice from index 1 to 3 (inclusive).

In [ ]:
a = np.arange(1,12,2)
print("Third element = ", end = " ")
print(a[2])
print("\nSlice form index 1 to 3 (inclusive) =", end= " ")
print(a[1:4])

Third element =  5

 Slice form index 1 to 3 (inclusive) = [3 5 7]


#**Intermediate NumPy Questions**

1. Create a 2D Numpy array of shape (3,3) with random integers between 1 and 10 (inclusive) using np.random.randint. Then, replace all values greater than 5 aith 0 and print the modified array.

In [ ]:
arr = np.random.randint(1,11,(3,3))
print(arr)
arr[arr>5] = 0
print("\nModified array:")
print(arr)


[[9 2 5]
 [9 1 2]
 [9 4 9]]

Modified array:
[[0 2 5]
 [0 1 2]
 [0 4 0]]


2. Create two 1D NumPy arrays: [2,4,6,8] and [1,3,5,7]. Compute the element-wise sum and the dot product of the two arrays. Print both results.


In [ ]:
a = np.array([2,4,6,8])
b = np.array([1,3,5,7])

sum = a+b
product = a*b
print(sum)
print(product)

[ 3  7 11 15]
[ 2 12 30 56]


3. Create a 2D NumPy array of shape (4,3) filled with ones using np.ones. Then, add a 1D array [10,20,30] to each row of the 2D array using broadcadting. Print the resulting array.

In [5]:
a = np.ones((4,3))
b = np.array([10,20,30])

new_arr = a+b
print(new_arr)

[[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]


4. Create a 2D NumPy array [[1,2,3],[4,5,6],[7,8,9]]. Extract the second column and compute its mean using np.mean. Then, reshape the original array into a 1D array and print both results.

In [8]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
mean_value = np.mean(a[:,1])
print(mean_value)

new_arr = np.array(a).reshape(-1)
print(new_arr)

5.0
[1 2 3 4 5 6 7 8 9]


5. Create a 1D NumPy array [10, 20, 30 ,40, 50, 60]. Use a boolean mask to select elements greater than 30, then square those elements. Print the original array and the modified array.

In [9]:
a = np.array([10, 20, 30 ,40, 50, 60])
mask = a>30
new_arr = a[mask]**2
print(a)
print(new_arr)

[10 20 30 40 50 60]
[1600 2500 3600]
